### ISSUE TITLE
unable to authenticate

### ISSUE THREAD

**Issue by jacobhash** [Kenkoman/B4v21#9]
I am trying to use regular authentication on v20 but it just says invalid key, also i dont want to link my blockland key and steam together to use it.

**Comment by Kenkoman** [comment]
key authentication on v20 works exactly as it does in v21. make sure your key works fine in v21 - afaik there shouldnt be any reason why it wouldnt work in v20 if it already works fine in v21

**Comment by jacobhash** [comment]
its working fine on normal blockland, it just says invalid key then i click retry and it shows my name but it still seems to be in demo mode.

**Comment by jacobhash** [comment]
Seems like using a different key works, i did test out changing my name on one client while playing on another than joining a server on both, could that be why it messed up? and is there any way to make my current key work?

**Comment by jacobhash** [comment]
Well my current key works on every version i have exept for v20, Why is that and is there any way to fix it?

**Comment by ClayHanson** [comment]
What are your BL_IDs for both keys? (and label which one works and which one doesn't)

**Comment by jacobhash** [comment]
Ok i have restored steam auth, but i joined irc and jia is the only one there

**Comment by ClayHanson** [comment]
okay, now use steam auth method again

**Comment by jacobhash** [comment]
still says invalid blid or name,heres some console stuff just incase you need it, Authentication: SUCCESS
Authentication: Connecting...
Authentication: Connecting...
Authentication FAILURE: no user
%

**Comment by ClayHanson** [comment]
This issue seems like it just loops around endlessly, so why not just use your other key?

**Comment by jacobhash** [comment]
Ok, i can do that until it gets fixed, we can keep in touch about it on irc or here if you want, thanks for helping, and yea that is quite weird behavior since it does show my name on regular auth on v20 yet it stays in demo mode.
